### ISSUE TITLE
网站后续的功能及发展讨论

### ISSUE THREAD

**Issue by imsobear** [imsobear/ituqu#2]
欢迎加入！

**Comment by songjiayang** [comment]
首先个人觉的是否该有个比较好的REDMINE.MD呢？关于项目说明，以及使用技术，如何部署，演示地址，怎么贡献代码，开源协议之类的呢？
类似于https://github.com/mistbow/cms_6bey ，如此一来，新来的人，也好快速上手，你说呢？

**Comment by imsobear** [comment]
哦， 我这两天就把这些东西添加了。
平时课很多～～～
